### ISSUE TITLE
simplify .load.bash file to work with different environments

### ISSUE THREAD

**Issue by TheRealBro** [keymon/password-store-for-teams#1]
atm - .load.bash is only working with bash

If password-store is installed from a proper package out of any distribution out there, there is no need to source bash-completion or zsh-completion files again, as they should live in the right place, where the regarding shell is expecting them for this distro.

therefore you could just use the following simple code for creating the aliases - works with ZSH and BASH and doesn't make a difference between those environments .. very useful for enterprise usage

Maybe you want to take this code instead of your complicated .load.bash script

```
for dirname in ~/.*-pass; do
  aliasname="${dirname#~/.}"
  alias $aliasname="PASSWORD_STORE_DIR=$dirname pass"
done
```

Kudos to @darix for helping with getting this solved^^

**Comment by TheRealBro** [comment]
@keymon are you still maintaining this tool :question:

**Comment by keymon** [comment]
Yes and not, there's not too much to maintain tbh :)

**Comment by TheRealBro** [comment]
Well I would like to help out, if you don't mind =).

**Comment by keymon** [comment]
Sure, feel free to send PRs :+1:

**Comment by keymon** [comment]
> If password-store is installed from a proper package out of any distribution out there, there is no need to source bash-completion or zsh-completion files again, as they should live in the right place, where the regarding shell is expecting them for this distro.

I can add a check if it is loaded. In my case it is not always loaded.

> therefore you could just use the following simple code for creating the aliases - works with ZSH and BASH and doesn't make a difference between those environments .. very useful for enterprise usage

But then I do not have completion for the aliases, do I?

**Comment by keymon** [comment]
Other thing this script does is that you can have the directory anywhere in any path. It will automatically detect the location, and define an alias. This was a requirement for some of my coworkers

The script you propose is assuming always $HOME

**Comment by TheRealBro** [comment]
Ok, than let's close this one for now, I will try to provide a PR or just fork to get our "corner-case" solved =).
Yes we mostly use it in out $HOME repos and tab-completion is a thing I wanted to add later.
For now it was the simplicity of the script I liked about the .load.bash file
